server:
  port: 8083

spring:
  application:
    name: cloud-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/      #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心

#放开所有节点
management:
  endpoints:
    web:
      exposure:
        include: '*'

zuul:
  routes:
    api:
      path: /api/**
      serviceId: cloud-client
    show:
      path: /show/**
      serviceId: cloud-client